export const SOCIAL_TEMPLATES = {
  ALL: { name: 'All Templates', width: 0, height: 0 },
  FACEBOOK_CAROUSEL: { name: 'Facebook Carousel Ad', width: 1080, height: 1080 },
  FACEBOOK_COVER: { name: 'Facebook Cover', width: 820, height: 312 },
  FACEBOOK_EVENT: { name: 'Facebook Event Cover Photo', width: 1920, height: 1005 },
  FACEBOOK_GROUP: { name: 'Facebook Group Cover Photo', width: 1640, height: 856 },
  FACEBOOK_PROFILE: { name: 'Facebook Profile Picture', width: 170, height: 170 },
  FACEBOOK_SHARED: { name: 'Facebook Shared Image Post', width: 1200, height: 630 },
  FACEBOOK_STORY_AD: { name: 'Facebook Story Ad', width: 1080, height: 1920 },
  GOOGLE_ADS: { name: 'Google Ads', width: 1200, height: 628 },
  INSTAGRAM_IGTV: { name: 'Instagram IGTV Cover', width: 420, height: 654 },
  INSTAGRAM_LANDSCAPE: { name: 'Instagram Landscape Post', width: 1080, height: 566 },
  INSTAGRAM_PORTRAIT: { name: 'Instagram Portrait Post', width: 1080, height: 1350 },
  INSTAGRAM_POST: { name: 'Instagram Post', width: 1080, height: 1080 },
  INSTAGRAM_STORY: { name: 'Instagram Story', width: 1080, height: 1920 },
  INSTAGRAM_STORY_AD: { name: 'Instagram Story Ad', width: 1080, height: 1920 },
  LINKEDIN_GROUP: { name: 'LinkedIn Group Banner', width: 1400, height: 425 },
  PINTEREST_LONG: { name: 'Pinterest Long Pin', width: 1000, height: 2100 },
  TELEGRAM_BANNER: { name: 'Telegram Channel Banner', width: 1280, height: 720 },
  TELEGRAM_PROFILE: { name: 'Telegram Profile Picture', width: 512, height: 512 },
  TELEGRAM_SHARED: { name: 'Telegram Shared Image', width: 1280, height: 1280 },
  TIKTOK_POST: { name: 'TikTok Post', width: 1080, height: 1920 },
  TIKTOK_PROFILE: { name: 'TikTok Profile', width: 200, height: 200 },
  TIKTOK_STORE_HEADER: { name: 'TikTok Store Product Header', width: 1200, height: 628 },
  TIKTOK_STORE_THUMB: { name: 'TikTok Store Product Thumbnail', width: 800, height: 800 },
  TWITTER_FLEET: { name: 'Twitter Fleet', width: 1080, height: 1920 },
  WHATSAPP_PROFILE: { name: 'WhatsApp Profile', width: 500, height: 500 },
  WHATSAPP_STATUS: { name: 'WhatsApp Status', width: 1080, height: 1920 },
  YOUTUBE_BANNER: { name: 'YouTube Channel Banner', width: 2560, height: 1440 },
  YOUTUBE_PLAYLIST: { name: 'YouTube Playlist Thumbnail', width: 1280, height: 720 },
  YOUTUBE_POST: { name: 'YouTube Post', width: 1280, height: 720 },
  YOUTUBE_SHORTS: { name: 'YouTube Shorts Thumbnail', width: 1080, height: 1920 }
};
