// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xyxpiinqnibqmosvndxv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh5eHBpaW5xbmlicW1vc3ZuZHh2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzUzOTA4MDgsImV4cCI6MjA1MDk2NjgwOH0.V8j-E7msDZg_4HcI7PbWOCXPI_gij5Bqz-OvI-ntCSE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);