// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yzmukkljzaqjtjcwumqx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl6bXVra2xqemFxanRqY3d1bXF4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzUxOTA2MDcsImV4cCI6MjA1MDc2NjYwN30.DyIuBOoLuI41HMIxtigzvjHWW69I4uFfWjdLhwZFOq4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);